### ISSUE TITLE
The stt integration does not support any configuration parameters

### ISSUE THREAD

**Issue by iz8mbw** [einToast/openai_stt_ha#8]
Hello.
Found this in the  home-assistant.log:

```
2025-05-06 16:18:17.108 ERROR (MainThread) [homeassistant.components.cloud] The stt integration does not support any configuration parameters, got [{'platform': 'openai_stt', 'api_key': 'LONG_API_KEY', 'model': 'gpt-4o-mini-transcribe', 'prompt': '', 'temperature': 0}]. Please remove the configuration parameters from your configuration.
```

This is what I inserted into configuration.yaml:

```
stt:                                                                                                                                    
  - platform: openai_stt                                                                                                                
    api_key: LONG_API_KEY
    #  Optional parameters                        
    model: gpt-4o-mini-transcribe                         
    prompt: ""                                
    temperature: 0                                                                             
```

Home Assistant version:
Core 2025.4.4
Supervisor 2025.04.1
Operating System 15.2
Frontend 20250411.0

Thanks.
